num1=input("enter no")
num2=input("enter no")
num3=input("enter no")
num4=input("enter no")
num5=input("enter no")
num6=input("enter no")
num7=input("enter no")
num8=input("enter no")

num9=input("enter no")
num10=input("enter no")

print(num1)
print(num2)
print(num3)
print(num4)
print(num5)
print(num6)
print(num7)
print(num8)
print(num9)
print(num10)
